name: "mnist_cnn"
platform: "pytorch_libtorch"
max_batch_size: 128
dynamic_batching { }
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
input [
  {
    name: "input__0"
    data_type: TYPE_FP32
    dims: [ 1, 28, 28 ]
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]
